// Generated by CoffeeScript 1.6.3
var app, authorization, env, errorHandling, express, fs, host, http, logging, nconf, path, selfMonitor, startServer;

fs = require('fs');

nconf = require('nconf');

nconf.argv().env();

nconf.defaults({
  host: 'localhost'
});

express = require('express');

http = require('http');

path = require('path');

logging = require('./logging');

errorHandling = require('./errorHandling');

authorization = require('./authorization');

app = express();

env = app.get('env');

logging.init();

logging.logGreen("Starting in mode " + env);

logging.log('Starting in mode ' + env);

host = nconf.get('host');

logging.logGreen('Using hostname ' + nconf.get('host'));

app.set('port', process.env.PORT || 80);

logging.logGreen('Using port ' + app.get('port'));

app.set('views', __dirname + '/views');

app.set('view engine', 'ejs');

app.use(express.favicon());

if (env === 'production') {
  app.use(express.logger('default'));
} else {
  app.disable('etag');
  app.use(express.logger('dev'));
}

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser('93AAAE3G205OI33'));

app.use(express.session());

app.use(app.router);

app.use(express["static"](path.join(__dirname, 'public')));

startServer = function() {
  var server, testFile, testUrl;
  server = http.createServer(app);
  server.timeout = 0;
  server.listen(app.get('port'), function() {
    return logging.logGreen('Server listening on port ' + app.get('port') + '....');
  });
  if (env !== 'production') {
    testFile = 'rwUEzeLnRfKgNh23R82W';
    return testUrl = 'http://localhost/handleInputFile?inkUrl=https://www.filepicker.io/api/file/' + testFile;
  }
};

selfMonitor = require('./selfMonitor').start();

startServer();
