// Generated by CoffeeScript 1.6.3
var app, authorization, env, errorHandling, express, fs, host, http, logging, nconf, path, selfMonitor, startServer;

fs = require('fs');

nconf = require('nconf');

nconf.argv().env();

nconf.defaults({
  host: 'localhost'
});

express = require('express');

http = require('http');

path = require('path');

logging = require('./logging');

errorHandling = require('./errorHandling');

authorization = require('./authorization');

logging.init();

app = express();

env = nconf.get('env');

logging.logGreen("Starting in mode " + env);

logging.log('Starting in mode ' + env);

host = nconf.get('host');

logging.logGreen('Using hostname ' + host);

app.set('port', process.env.PORT || 80);

logging.logGreen('Using port ' + app.get('port'));

app.set('views', __dirname + '/views');

app.set('view engine', 'ejs');

app.use(express.favicon());

if (env === 'production') {
  app.use(express.logger('default'));
  app.use(express.basicAuth(function(user, pass) {
    if (user === 'demo' && pass === 'articlio') {
      console.log('user authenticated through basic auth');
      return true;
    } else {
      console.log("user failed authenticating through basic auth - failed username was " + user);
      return false;
    }
  }));
} else {
  app.disable('etag');
  app.use(express.logger('dev'));
}

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser('93AAAE3G205OI33'));

app.use(express.session());

app.use(app.router);

app.use(express["static"](path.join(__dirname, 'public')));

app.get('/getData', require('./ajax/getMockData').get);

startServer = function() {
  var server;
  server = http.createServer(app);
  server.timeout = 0;
  return server.listen(app.get('port'), function() {
    return logging.logGreen('Server listening on port ' + app.get('port') + '....');
  });
  /* 
  # In dev mode, self-test on startup
  #
  unless env is 'production' 
  
    testFile = 'rwUEzeLnRfKgNh23R82W'
    testUrl = 'http://localhost/handleInputFile?inkUrl=https://www.filepicker.io/api/file/' + testFile
    http.get(testUrl, (res) ->
      logging.logBlue 'Server response to its own synthetic client is: ' + res.statusCode)
  */

};

selfMonitor = require('./selfMonitor').start();

startServer();
