// Generated by CoffeeScript 1.6.3
var fs;

fs = require('fs');

exports.get = function(req, res) {
  var err, jsonFile, path, text;
  if (req.query.data != null) {
    path = './mock-data';
    jsonFile = req.query.data;
    try {
      text = fs.readFileSync(path + '/' + jsonFile + '.json').toString();
    } catch (_error) {
      err = _error;
      if (err.code === 'ENOENT') {
        res.send(404);
        throw 'could not fetch data for ' + req.query.data;
      } else {
        throw e;
      }
    }
    return res.end(text);
  } else {
    console.log('unidentified query');
    return res.send(400);
  }
};
