// Generated by CoffeeScript 1.6.3
({
  "names": ["abstract", "cloud view", "limitations of study", "author's purpose", "research questions/hypotheses", "introduction summary", "conclusions summary"]
});
